name: Build and Deploy Vignette

on:
  push:
    branches: [main]  # or your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev pandoc

    - name: Install R dependencies
      run: |
        install.packages("BiocManager")
        BiocManager::install(c("devtools", "rmarkdown", "BiocStyle"), ask = FALSE, update = FALSE)
      shell: Rscript {0}

    - name: Install package with vignettes
      run: |
        devtools::install(".", build_vignettes = TRUE, dependencies = TRUE)
      shell: Rscript {0}

    - name: Copy built vignette to deploy directory
      run: |
        mkdir deploy
        cp doc/IEOProjectAnalysis.html deploy/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
